SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


# PLAYER DATA
PLAYER_RADIUS = 20
PLAYER_COLOR = "white"
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


#ASTEROID DATA
ASTEROID_RADIUS = 40
ASTEROID_COLOR="red"
ASTEROID_SPEED = 150
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
